### ISSUE TITLE
Missing #to_s in file provider

### ISSUE THREAD

**Issue by andis** [sometimesfood/wright#1]
When updating existing files, wright fails with the following error message due to a missing `to_s`:

```
INFO: create file: 'foo'
ERROR: file 'foo': can't convert Time into String
wright/lib/wright/provider/file.rb:77:in `digest': can't convert Time into String (TypeError)
        from wright/lib/wright/provider/file.rb:77:in `hexdigest'
        from wright/lib/wright/provider/file.rb:77:in `checksum'
        from wright/lib/wright/provider/file.rb:83:in `content_uptodate?'
        from wright/lib/wright/provider/file.rb:89:in `uptodate?'
        from wright/lib/wright/provider/file.rb:19:in `create'
        from wright/lib/wright/resource/file.rb:51:in `block in create'
        from wright/lib/wright/resource.rb:107:in `might_update_resource'
        from wright/lib/wright/resource/file.rb:50:in `create'
        from wright/lib/wright/resource.rb:72:in `run_action'
        from wright/lib/wright/dsl.rb:60:in `yield_resource'
        from wright/lib/wright/dsl.rb:45:in `block in register_resource'
        from ./bug-repro:9:in `<main>'
```

How to reproduce:

``` ruby
require 'wright'                                                                                                                                                                
extend Wright::DSL                                                                      

file('foo') do |f|                                                                      
  f.content = Time.now                                                                  
end                                                                                     

file('foo') do |f|                                                                      
  f.content = Time.now                                                                  
end
```

**Comment by sometimesfood** [comment]
Thanks, fix incoming.
