### ISSUE TITLE
bin/wright does not support the DSL in -e commands

### ISSUE THREAD

**Issue by sometimesfood** [sometimesfood/wright#4]
The wright binary does not support the DSL in `-e` commands.

How to reproduce:

```
$ bundle exec bin/wright -e 'directory "/tmp/foobar"'
```

Expected output:

```
INFO: create directory: '/tmp/foobar'
```

Actual output:

```
<main>:1:in `run': undefined method `directory' for #<Wright::CLI:0x007fb5d1adb748> (NoMethodError)
        from /Users/sebastian/src/wright/lib/wright/cli.rb:32:in `eval'
        from /Users/sebastian/src/wright/lib/wright/cli.rb:32:in `run'
        from bin/wright:5:in `<main>'
```

**Comment by sometimesfood** [comment]
@andis: Does 0bac6251def975a8e2f1f347747e549e16741c1e look reasonable to you?

This should be a little more explicit and also has the added benefit of producing slightly cleaner error messages:

```
~/src/wright (git)-[dsl-in-e-commands] % bundle exec bin/wright -e 'foobar'
<main>:1:in `run': undefined local variable or method `foobar' for main:Object (NameError)
        from /Users/sebastian/src/wright/lib/wright/cli.rb:32:in `instance_eval'
        from /Users/sebastian/src/wright/lib/wright/cli.rb:32:in `run'
        from bin/wright:5:in `<main>
```

**Comment by andis** [comment]
Yes, looks reasonable.

**Comment by sometimesfood** [comment]
Cheers.
